### ISSUE TITLE
magnetometer_serial_microbit_v2 example mag reading not updating.

### ISSUE THREAD

**Issue by llbsh** [fduignan/zephyr_bbc_microbit_v2#1]
Hello Frank, 

Thanks for sharing the examples of Zephyr with microbit_v2. I was also trying to enable magnetometer recently. I build your magnetometer example code with last main branch of Zephyr (b1b977dacf), and flash to my V2 board, however, the readings does not update, the uart output is: 

*** Booting Zephyr OS build zephyr-v2.6.0-1632-gb1b977dacf96  ***
Hello World! bbc_microbit_v2
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500
X: -0.147000, Y: 0.159000, Z: 0.412500

Could you give some advice about what the issue is? 

Thanks,
Nathan

**Comment by fduignan** [comment]
Hi Nathan, could you please try the following:
In the main function you will see that a line has been commented out:
//      ret = i2c_write(i2c_dev, buf, 2, 0x1e);  // power up the magnetometer (driver is broken)
Can you remove the "//" i.e. un-comment it and see if your values change.
If this works then the branch you have is behind the version lis2mdl driver on github.  
I re-installed zephyr and it appeared to pull in the later version of the driver.

**Comment by fduignan** [comment]
I have replied via a github comment - hope you got it.

**Comment by fduignan** [comment]
I haven't heard any follow up on this so I've concluded that the matter is closed
